# Supabase Configuration
REACT_APP_SUPABASE_URL=https://extwgzhlwickiuiuhzaf.supabase.co
REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4dHdnemhsd2lja2l1aXVoemFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDgwMjksImV4cCI6MjA2ODU4NDAyOX0.xPlHFYap2aBjj8F4OFaPJw0k-tjiI0Eg_9dWlxTt6iw

# WhatsApp Configuration
REACT_APP_WHATSAPP_NUMBER=393356222225

# App Configuration
REACT_APP_APP_NAME=MyDivinos
